config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "customers#index"
  resources :customers do
    collection do
      get 'search'
    end
    resources :dailies, only: [:index, :new, :create , :edit, :update]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '特別養護老人ホーム' },
    { id: 2, name: 'サービス付き高齢者向け住宅' },
    { id: 3, name: '有料老人ホーム' },
    { id: 4, name: 'デイサービス' },
    { id: 5, name: 'グループホーム' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :customers
end

app/models/contract.rb
class Contract < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '新規' },
    { id: 2, name: '既存' }
  ]

  include ActiveHash::Associations
  has_many :customers
end

app/models/customer.rb
class Customer < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :dailies, dependent: :destroy
  belongs_to :user

  belongs_to :category
  belongs_to :prefecture
  belongs_to :contract

  def self.search(search)
    if search != ''
      Customer.where('customer_name LIKE(?)', "%#{search}%")
    else
      Customer.all
    end
  end

  with_options presence: true do
    validates :customer_name
    validates :postcode, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'はハイフンを含めた半角文字列で入力してください (例：123-4567)' }
    validates :city
    validates :block
    validates :phone_number, format: { with: /\A[0-9]{10,11}+\z/, message: 'は10桁以上11桁以内の半角数字で入力してください' }
    validates :capacity, numericality: { only_integer: true }
  end

  with_options numericality: { other_than: 0, message: 'を選択してください' } do
    validates :category_id
    validates :prefecture_id
    validates :contract_id
  end
end

app/models/daily.rb
class Daily < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :customer
  belongs_to :user

  belongs_to :meal

  with_options presence: true do
    validates :meet_year, numericality: { only_integer: true, greater_than: 2023, less_than_or_equal_to: 2030 }
    validates :meet_month, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 12 }
    validates :meet_day, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 31 }
    validates :text
  end

  with_options numericality: { other_than: 0, message: 'を選択してください' } do
    validates :meal_id
  end
end

app/models/meal.rb
class Meal < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: 'クックフリーズ' }, { id: 2, name: 'クックチル' },
    { id: 3, name: 'クックサーブ' }, { id: 4, name: '業務委託' }, { id: 5, name: 'お弁当' },
    { id: 6, name: '手作り' }, { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :dailies
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customers
  has_many :dailies

  with_options presence: true do
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
    validates_format_of :password, with: PASSWORD_REGEX, message: 'は英数字の混合である必要があります'
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :office_name
    validates :birthday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:last_name, :first_name, :office_name, :birthday])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  def index
    @customer = Customer.includes(:user).order('created_at DESC')
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    if @customer.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @daily = Daily.new
  end

  def search
    @customer = Customer.search(params[:keyword])
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @customer.destroy
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:customer_name, :category_id, :postcode, :prefecture_id, :city, :block, :building,
                                     :phone_number, :capacity, :contract_id, :remarks_column).merge(user_id: current_user.id)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]
  before_action :set_daily, only: [:index, :new]

  def index
    @dailies = @customer.dailies.includes(:user).order('created_at DESC')
  end

  def new
    @daily = Daily.new
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @daily = Daily.new(daily_params)
    if @daily.save
      redirect_to "/customers/#{@daily.customer.id}/dailies"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def daily_params
    params.require(:daily).permit(:meet_year, :meet_month, :meet_day, :manager_name, :meal_id, :competitor, :text).merge(
      user_id: current_user.id, customer_id: params[:customer_id]
    )
  end

  def set_daily
    @customer = Customer.find(params[:customer_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :office_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/edit.html.erb
<%= render "shared/form_header" %>
<div class="new-title">顧客編集フォーム</div>
<%= form_with model: @customer, local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>

<div class="Form">
  <div class="Form-Item">
    <p class="Form-Item-Label">
      <span class="Form-Item-Label-Required">必須</span>施設名
    </p>
    <%= f.text_field :'customer_name', class:"Form-Item-Input", id:"customer_name", placeholder:"例）デイサービス○○" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>種類</p>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>入居定員</p>
    <%= f.text_field :'capacity', class:"Form-Item-Input", id:"capacity", placeholder:"例）20" %>
    <span class = cap>名</span>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>顧客状況</p>
    <%= f.collection_select(:contract_id, Contract.all, :id, :name, {}, {class:"select-box", id:"contract"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>郵便番号</p>
    <%= f.text_field :'postcode', class:"Form-Item-Input", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>都道府県</p>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>市区町村</p>
    <%= f.text_field :city, class:"Form-Item-Input", id:"city", placeholder:"例）大阪市中央区"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>番地</p>
    <%= f.text_field :'block', class:"Form-Item-Input", id:"addresses", placeholder:"例）土井1-1-1"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">任意</span>建物名</p>
    <%= f.text_field :'building', class:"Form-Item-Input", id:"building", placeholder:"例）土井ビル103"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>施設電話番号</p>
    <%= f.text_field :'phone_number', class:"Form-Item-Input", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">任意</span>備考欄</p>
    <%= f.text_area :'remarks_column', class:"Form-Item-Input", id:"remarks_column", placeholder:"例）2024年から取引開始" %>
  </div>
  <%= f.submit "編集する", class:"Form-Btn", id:"form-button"%>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/customers/index.html.erb
<%= render "shared/header" %>
<% if @customer.blank? %>
  <div class="customer-none-contents">
    <div class="customer-none-title"><%= "現在、顧客情報はありません。"%></div>
  </div>
<% else %>
  <div class="index-customer-title">顧客一覧</div>
  <div class="flex-table">
    <div class="flex-row">
      <div class="flex-cell header">施設名</div>
      <div class="flex-cell header">種類</div>
      <div class="flex-cell header">施設所在地</div>
      <div class="flex-cell header">入居定員</div>
      <div class="flex-cell header">顧客情報</div>
      <div class="flex-cell header">商談履歴</div>
    </div>
    <% @customer.each do |customer| %>
    <div class="flex-row">
      <div class="flex-cell"><%= customer.customer_name %></div>
      <div class="flex-cell"><%= customer.category.name %></div>
      <div class="flex-cell"><%= customer.prefecture.name %></div>
      <div class="flex-cell"><%= customer.capacity %><span>名</span></div>
      <div class="flex-cell"><%= link_to(customer_path(customer.id), class: 'customer-show-btn') do %>
        <span class='customer-show-text'>詳細</span><% end %></div>
    <div class="flex-cell"><%= link_to(customer_dailies_path(customer.id), class: 'daily-show-btn') do %>
        <span class='customer-show-text'>詳細</span><% end %></div>
        </div>
    <% end %>
  </div>
<% end %>

<div class="customer-new-item">
  <%= link_to(new_customer_path, class: 'customer-new-btn') do %>
    <span class='customer-new-text'>顧客登録</span>
  <% end %>
</div>


<%= render "shared/footer" %>

app/views/customers/new.html.erb
<%= render "shared/form_header" %>
<div class="new-title">顧客登録フォーム</div>
<%= form_with model: @customer, local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
<div class="Form">
  <div class="Form-Item">
    <p class="Form-Item-Label">
      <span class="Form-Item-Label-Required">必須</span>施設名
    </p>
    <%= f.text_field :'customer_name', class:"Form-Item-Input", id:"customer_name", placeholder:"例）デイサービス○○" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>種類</p>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>入居定員</p>
    <%= f.text_field :'capacity', class:"Form-Item-Input", id:"capacity", placeholder:"例）20" %>
    <span class = cap>名</span>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>顧客状況</p>
    <%= f.collection_select(:contract_id, Contract.all, :id, :name, {}, {class:"select-box", id:"contract"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>郵便番号</p>
    <%= f.text_field :'postcode', class:"Form-Item-Input", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>都道府県</p>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>市区町村</p>
    <%= f.text_field :city, class:"Form-Item-Input", id:"city", placeholder:"例）大阪市中央区"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>番地</p>
    <%= f.text_field :'block', class:"Form-Item-Input", id:"addresses", placeholder:"例）土井1-1-1"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">任意</span>建物名</p>
    <%= f.text_field :'building', class:"Form-Item-Input", id:"building", placeholder:"例）土井ビル103"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>施設電話番号</p>
    <%= f.text_field :'phone_number', class:"Form-Item-Input", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">任意</span>備考欄</p>
    <%= f.text_area :'remarks_column', class:"Form-Item-Input", id:"remarks_column", placeholder:"例）2024年から取引開始" %>
  </div>
  <%= f.submit "登録する" ,class:"Form-Btn", id:"form-button" %>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/customers/search.html.erb
<%= render "shared/header" %>
<div class="search-title">検索結果</div>
<div class="flex-table">
  <div class="flex-row">
    <div class="flex-cell header">施設名</div>
    <div class="flex-cell header">種類</div>
    <div class="flex-cell header">施設所在地</div>
    <div class="flex-cell header">入居定員</div>
    <div class="flex-cell header">顧客情報</div>
    <div class="flex-cell header">商談履歴</div>
  </div>
  <% @customer.each do |customer| %>
  <div class="flex-row">
    <div class="flex-cell"><%= customer.customer_name %></div>
    <div class="flex-cell"><%= customer.category.name %></div>
    <div class="flex-cell"><%= customer.prefecture.name %></div>
    <div class="flex-cell"><%= customer.capacity %><span>名</span></div>
    <div class="flex-cell"><%= link_to(customer_path(customer.id), class: 'customer-show-btn') do %>
      <span class='customer-show-text'>詳細</span><% end %></div>
    <div class="flex-cell"><%= link_to(customer_dailies_path(customer.id), class: 'daily-show-btn') do %>
      <span class='customer-show-text'>詳細</span><% end %></div>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/customers/show.html.erb
<%= render "shared/form_header"%>
<div class="show-title"><%="#{@customer.customer_name}の詳細情報"%></div>

<div class="item-show">
  <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-customer">施設名</th>
          <td class="detail-value"><%= @customer.customer_name %></td>
        </tr>
        <tr>
          <th class="detail-customer">種類</th>
          <td class="detail-value"><%= @customer.category.name %></td>
        </tr>
        <tr>
          <th class="detail-customer">顧客区分</th>
          <td class="detail-value"><%= @customer.contract.name %></td>
        </tr>
        <tr>
          <th class="detail-customer">施設所在地</th>
          <td class="detail-value">〒<%= @customer.postcode %> <%= @customer.prefecture.name%><%= @customer.city %><%= @customer.block %><%= @customer.building %> </td>
        </tr>
        <tr>
          <th class="detail-customer">電話番号</th>
          <td class="detail-value"><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th class="detail-customer">定員</th>
          <td class="detail-value"><%= @customer.capacity %>名</td>
        </tr>
        <tr>
          <th class="detail-customer">備考</th>
          <td class="detail-value"><%= @customer.remarks_column %></td>
        </tr>
        <tr>
          <th class="detail-customer">操作</th>
          <td class="detail-value">
          <%= link_to(edit_customer_path(@customer.id), class: 'customer-edit-btn', id:"customer-edit-button") do %>
          <span class='customer-edit-text'>編集</span>
          <% end %>
          </td>
        </tr>
      </tbody>
    </table>
</div>

<%= render "shared/footer" %>

app/views/dailies/index.html.erb
<%= render "shared/second_header"%>

<% if @dailies.nil? || @dailies.empty? %>
  <div class="daily-none-title"><%= "現在、#{@customer.customer_name}の商談履歴はありません。"%></div>
<% else %>
  <div class="daily-index-title"><%= "#{@customer.customer_name}の商談履歴"%></div>
  <% @dailies.each do |daily| %>
  <div class ="daily-index-item">
  <ul class="daily-index-list">
    <li class="daily-list">商談日：<%= "#{daily.meet_year}年#{daily.meet_month}月#{daily.meet_day}日" %></li>
    <li class="daily-list">営業担当：<%= "#{daily.user.last_name} #{daily.user.first_name}" %></li>
    <li class="daily-list">所属部署：<%= daily.user.office_name %></li>
    <li class="daily-list">施設担当者：<%= daily.manager_name %></li>
    <li class="daily-list">食事内容：<%= daily.meal.name %></li>
    <li class="daily-list">業者名：<%= daily.competitor %></li>
    <li class="daily-list">商談内容：<%= daily.text %></li>
  </ul>
  </div>
  <% end %>
<% end %>
<div class="daily-new-item">
<%= link_to(new_customer_daily_path(@customer.id), class: 'daily-new-btn') do %>
      <span class='daily-new-text'>商談入力</span><% end %>
</div>
<%= render "shared/footer" %>

app/views/dailies/new.html.erb
<%= render "shared/form_header"%>

<div class="daily-new-title"><%= "#{@customer.customer_name}の日報入力"%></div>
  <%= form_with(model: [@customer, @daily], method: :post) do |f| %>
<%= render 'shared/error_messages', model: f.object %>
<div class="Form">
  <div class="Form-Item">
    <p class="Form-Item-Label">
      <span class="Form-Item-Label-Required">必須</span>商談日(半角数字)
    </p>
      <%= f.number_field :meet_year, class:"form-item-input", id:"meet_year", placeholder:"年", min: 2024, max: 2030, required: true %>
      <%= f.number_field :'meet_month', class:"form-item-input", id:"meet_month", placeholder:"月", min: 1, max: 12, required: true %>
      <%= f.number_field :'meet_day', class:"form-item-input", id:"meet_day", placeholder:"日", min: 1, max: 31, required: true %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>施設担当者</p>
    <%= f.text_field :'manager_name', class:"Form-Item-Input", id:"manager_name", placeholder:"例）山本" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>食事内容</p>
    <%= f.collection_select(:meal_id, Meal.all, :id, :name, {}, {class:"select-box", id:"meal"}) %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required">任意</span>食事業者</p>
    <%= f.text_field :'competitor', class:"Form-Item-Input", id:"competitor", placeholder:"例）タイヘイ" %>
  </div>
  <div class="Form-Item">
    <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>商談内容</p>
    <%= f.text_area :'text', class:"Form-Item-Input", id:"text", placeholder: "例）今月中に契約締結し、来月から導入開始予定" %>
  </div>
  <%= f.submit "登録する" ,class:"Form-Btn", id:"form-button" %>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailyreport41465</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='customer-details'>
    <h4 class='footer-content-head'>営業日報管理システムについて</h4>
    <ul>
      <li><%= link_to 'システム利用ガイド', "#", class: "footer-link", id: "footer-guide" %></li>
      <li><%= link_to 'ガイドライン', "#", class: "footer-link", id: "footer-guideline" %></li>
      <li><%= link_to 'お知らせ', "#", class: "footer-link", id: "footer-news" %></li>
    </ul>
  </div>
  <p>© DoiMasaru Co., Ltd. All Rights Reserved. </p>
</div>

app/views/shared/_form_header.html.erb
<header class='form-header'>
  <%= link_to image_tag("logo_loading.png", class:"form-logo"), "/" %>
  <div class="form-bar">
  </div>
</header>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo_loading.png", class:"corp-icon"), "/" %>
    <div class="title">営業日報管理システム</div>
    <%= form_with(url: search_customers_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder:"施設名から検索", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn", id:"search-button" %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="menu-bar">
      <ul class="menu-elements">
        <li id="menu1">
          <div class ="user-name"><%= "#{current_user.last_name}#{current_user.first_name}"%></div>
          <ul class="menu1-lists hidden" id="menu1-pull-down">
            <li><%= link_to "マイページ", "/users/#{current_user.id}", class: "my-page" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout" %></li>
          </ul>
        </li>
        <li id="menu2">
          メニュー
          <ul class="menu2-lists hidden" id="menu2-pull-down">
            <li><%= link_to(new_customer_path, class: 'customer-new-btn') do %>
              <span class='customer-new-text'>顧客登録</span>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="menu-bar">
      <ul class="menu-elements">
        <li id="menu1">
          <%= link_to "ログイン", new_user_session_path, class: "login" %>
        </li>
        <li id="menu2">
          <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
        </li>
      </ul>
    </div>
  <% end %>
</header>

app/views/shared/_second_header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo_loading.png", class:"second-logo"), "/" %>

      <div class="menu-bar">
      <ul class="menu-elements">
        <li id="menu3">
          メニュー
          <ul class="menu3-lists hidden" id="menu3-pull-down">
            <li><%= link_to(new_customer_daily_path(@customer.id), class: 'daily-new-btn', id:"daily-new-button") do %>
              <span class='daily-new-text'>商談入力</span>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
</header>

app/views/users/show.html.erb
<%= render "shared/form_header"%>
<div class="user-title">マイページ</div>


<div class="user-show">
  <table class="user-detail-table">
      <tbody>
        <tr>
          <th class="detail-user">名前</th>
          <td class="detail-value"><%= "#{@user.last_name} #{@user.first_name}" %></td>
        </tr>
        <tr>
          <th class="detail-user">所属</th>
          <td class="detail-value"><%= @user.office_name %></td>
        </tr>
        <tr>
          <th class="detail-user">メールアドレス</th>
          <td class="detail-value"><%= @user.email %></td>
        </tr>
      </tbody>
    </table>
</div>

  <%= render "shared/footer" %>